version: '3.4'

services:
    # Simple setup
    # nginx:
    #     image: nginx
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/nginx.conf
    #     ports:
    #         - 8081:8081

    # Setup via Dockerfile
    nginx:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8081:8081
